name:                grpc-etcd-client
version:             0.1.0.2
github:              "lucasdicioccio/grpc-etcd-client"
license:             BSD3
author:              "Lucas DiCioccio"
maintainer:          "lucas@dicioccio.fr"
copyright:           "2018 Lucas DiCioccio"
homepage:       https://github.com/lucasdicioccio/etcd-grpc#readme
bug-reports:    https://github.com/lucasdicioccio/etcd-grpc/issues
github:         lucasdicioccio/etcd-grpc

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            gRPC client for etcd
category:            Distributed Computing

description:         Please see the README on GitHub at <https://github.com/lucasdicioccio/etcd-grpc#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- data-default-class
- grpc-api-etcd == 0.1.0.1
- http2-client
- http2-client-grpc >= 0.5 && < 0.6
- lens
- network
- proto-lens
- proto-lens-protoc

default-extensions:
- DataKinds
- OverloadedStrings

library:
  source-dirs: src
