name:                grpc-etcd-client
version:             0.1.0.0
github:              "lucasdicioccio/grpc-etcd-client"
license:             BSD3
author:              "Lucas DiCioccio"
maintainer:          "lucas@dicioccio.fr"
copyright:           "2018 Lucas DiCioccio"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            gRPC client for etcd
category:            Distributed Computing

description:         Please see the README on GitHub at <https://github.com/lucasdicioccio/grpc-etcd-client#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- data-default-class
- grpc-api-etcd
- http2-client
- http2-client-grpc
- lens
- network
- proto-lens
- proto-lens-protoc

default-extensions:
- DataKinds
- OverloadedStrings

library:
  source-dirs: src
